#!/usr/bin/env python3
"""Backfill per-day LLM attribution into published summary.json files.

Each web/data/{date}/summary.json gains llm_model + llm_model_display so the
frontend can show which engine produced that day's report ("Generated by ...").
Evidence sources, in order:

  1. replay-index.json run.models -- exact per-day truth (2026-07-27 onward).
  2. Era table below -- reconstructed from git history of the pipeline config
     (config/providers.yaml.example + .github/workflows/daily-pipeline.yml
     model-default changes). Boundaries are the switch-commit dates, so a
     boundary day can be off by one report.

Days whose model cannot be determined are left untouched and reported, so the
frontend's neutral fallback shows instead of a wrong claim.

Run from the repo root:
    python3 scripts/backfill_model_display.py [--dry-run]
"""

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DATA_DIR = REPO / "web" / "data"

# Era table: (first report date on this engine, representative model id).
# Provenance: git log of config/providers.yaml.example and the daily workflow.
# NOTE: a brief Claude Fable 5 experiment around 2026-06-10 lived only in the
# secret-held providers config and left no trace in tracked history -- days in
# that window are labeled with the surrounding era until given exact dates.
ERAS = [
    ("2025-12-26", "claude-4.7-opus-aws", "Claude Opus 4.7"),
    ("2026-05-28", "claude-4.8-opus-aws", "Claude Opus 4.8"),
    ("2026-07-27", "claude-5-opus-aws", "Claude Opus 5"),
    ("2026-08-22", "stealth/ox-alpha", "Ox Alpha"),
]


def display_name_for(model_id: str) -> str:
    """Human-facing name for any model id seen in this pipeline's history."""
    mid = model_id.lower()
    if "ox-alpha" in mid:
        return "Ox Alpha"
    if "claude-5-opus" in mid or "claude-opus-5" in mid:
        return "Claude Opus 5"
    if "fable" in mid:
        return "Claude Fable 5"
    if "claude-4.8" in mid or "claude-4-8" in mid:
        return "Claude Opus 4.8"
    if "claude-4.7" in mid or "claude-4-7" in mid:
        return "Claude Opus 4.7"
    return model_id


def is_image_model(model_id: str) -> bool:
    """Image generators share replay run.models with the LLM; keep the LLM."""
    last = model_id.rsplit("/", 1)[-1].lower()
    return "image" in last or "gemini" in last


def model_from_replay(date_dir: Path) -> str | None:
    path = date_dir / "replay-index.json"
    if not path.exists():
        return None
    try:
        models = (json.loads(path.read_text(encoding="utf-8"))
                  .get("run", {}).get("models") or [])
    except Exception as exc:  # noqa: BLE001 - a corrupt artifact must not abort
        print(f"  ! {date_dir.name}: unreadable replay-index.json: {exc}")
        return None
    for model_id in models:
        if not is_image_model(model_id):
            return model_id
    return None


def model_from_eras(date: str) -> tuple[str, str] | None:
    chosen = None
    for start, model_id, display in ERAS:
        if date >= start:
            chosen = (model_id, display)
    return chosen


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="report what would change without writing")
    args = parser.parse_args()

    stamped = era_stamped = skipped = already = 0

    for date_dir in sorted(DATA_DIR.iterdir()):
        if not date_dir.is_dir() or len(date_dir.name) != 10:
            continue
        summary_path = date_dir / "summary.json"
        if not summary_path.exists():
            continue
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        if summary.get("llm_model"):
            already += 1
            continue

        date = date_dir.name
        model_id = model_from_replay(date_dir)
        source = "replay"
        if model_id is None:
            era = model_from_eras(date)
            if era is None:
                skipped += 1
                print(f"  ? {date}: no evidence, leaving unstamped")
                continue
            model_id, display = era
            source = "era"
        else:
            display = display_name_for(model_id)

        if source == "replay":
            stamped += 1
        else:
            era_stamped += 1
        print(f"  {date}: {model_id} ({display}) [{source}]")
        if not args.dry_run:
            summary["llm_model"] = model_id
            summary["llm_model_display"] = display
            summary_path.write_text(
                json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
                encoding="utf-8",
            )

    print(f"\nDone: {stamped} from replay evidence, {era_stamped} from eras, "
          f"{already} already stamped, {skipped} skipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
