"""Probe LessWrong through every Mullvad exit to build a known-good pool.

LessWrong's Vercel edge blocks by exit-IP reputation; on 2026-08-09 most
sampled US exits drew 429s while us-atl-wg-401 answered 200. The CI tunnel
step rotates relays until its probe passes, but with most of the pool blocked
it can burn its whole attempt budget on duds. This sweep tests every exit and
writes the winners to config/mullvad_good_relays.txt, which the tunnel step
tries first.

HOW IT PROBES — one tunnel, many exits. Mullvad runs a SOCKS5 endpoint for
every WireGuard relay, reachable from INSIDE any connected tunnel as
<relay>-socks5-<nnn>.relays.mullvad.net:1080 (us-atl-wg-001 ->
us-atl-wg-socks5-001). So the sweep connects the local Mullvad app once and
probes every other exit through per-relay SOCKS, never touching the machine's
own connectivity again. (The first version of this script reconnected the VPN
per relay — 200+ reconnects — which repeatedly dropped the whole machine's
network. Do not go back to that.)

One GraphQL POST per exit, same fingerprint as the pipeline's first-try path.

Usage:
  # 1. Connect Mullvad to any relay first (mullvad connect)
  # 2. python3 scripts/sweep_mullvad_relays.py [--filter us] [--workers 8]

Requires PySocks (requests[socks]); pipeline requirements.txt already has it.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parents[1]

GRAPHQL_URL = "https://www.lesswrong.com/graphql"
USER_AGENT = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
)
QUERY = '{ posts(input: { terms: { view: "new", limit: 1 } }) { results { _id } } }'
PROBE_TIMEOUT_S = 20


def relay_hostnames(country_filter: str) -> list[str]:
    out = subprocess.run(
        ["mullvad", "relay", "list"], capture_output=True, text=True, timeout=60
    ).stdout
    return re.findall(rf"\b({country_filter}-[a-z]{{3}}-wg-[0-9]+)\b", out)


def socks_name(relay: str) -> str:
    """us-atl-wg-001 -> us-atl-wg-socks5-001.relays.mullvad.net"""
    prefix, number = relay.rsplit("-", 1)
    return f"{prefix}-socks5-{number}.relays.mullvad.net"


def probe(relay: str) -> tuple[str, str]:
    proxy = f"socks5h://{socks_name(relay)}:1080"
    try:
        response = requests.post(
            GRAPHQL_URL,
            json={"query": QUERY},
            headers={"User-Agent": USER_AGENT},
            proxies={"http": proxy, "https": proxy},
            timeout=PROBE_TIMEOUT_S,
        )
    except Exception:
        return relay, "unreachable"  # no SOCKS endpoint for this relay, or timeout

    if response.status_code == 200:
        try:
            payload = json.loads(response.text)
        except ValueError:
            return relay, "blocked"  # challenge interstitial served with a 200
        if isinstance(payload, dict) and payload.get("data") and not payload.get("errors"):
            return relay, "ok"
        return relay, "invalid"
    if response.status_code in (403, 429):
        return relay, "blocked"
    return relay, "invalid"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--filter", default="us")
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument(
        "--out", default=str(REPO_ROOT / "config" / "mullvad_good_relays.txt")
    )
    args = parser.parse_args()

    status = subprocess.run(
        ["mullvad", "status"], capture_output=True, text=True, timeout=30
    ).stdout
    if "Connected" not in status:
        print(
            "Mullvad is not connected. Per-relay SOCKS endpoints are only reachable "
            "from inside a tunnel — run `mullvad connect` first.",
            file=sys.stderr,
        )
        return 2

    relays = relay_hostnames(args.filter)
    if not relays:
        print("no relays matched the filter", file=sys.stderr)
        return 2

    print(f"probing {len(relays)} exits through the current tunnel "
          f"({args.workers} at a time)")
    started = time.time()
    results: dict[str, str] = {}
    with ThreadPoolExecutor(max_workers=args.workers) as pool:
        for relay, verdict in pool.map(probe, relays):
            results[relay] = verdict
            print(f"  {relay}: {verdict}")

    good = sorted(r for r, v in results.items() if v == "ok")
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y-%m-%d", time.gmtime())
    with out_path.open("w", encoding="utf-8") as handle:
        handle.write(
            f"# Mullvad relays whose exit IPs LessWrong answered (HTTP 200) on {stamp}.\n"
            "# Generated by scripts/sweep_mullvad_relays.py — the CI tunnel step tries\n"
            "# these first, in order, before the rest of the sorted relay list.\n"
            "# Blocklists drift; refresh when LessWrong goes quiet again.\n"
        )
        for relay in good:
            handle.write(relay + "\n")

    counts: dict[str, int] = {}
    for verdict in results.values():
        counts[verdict] = counts.get(verdict, 0) + 1
    print(f"\ndone in {(time.time() - started) / 60:.1f} min: {counts}")
    print(f"{len(good)} good relays -> {out_path}")
    return 0 if good else 1


if __name__ == "__main__":
    sys.exit(main())
